### ISSUE TITLE
implement directives for other JS components

### ISSUE THREAD

**Issue by newmanw** [krescruz/angular-materialize#1]
Any plans to implement directives for the other JS components?

I can try to help, but not an angular expert by any means ;)

Love the materialize framework and would love to see angular directives.

**Comment by webbiesdk** [comment]
I just created a pull request #2 that adds more directives, maybe some of it is what you are looking for. 

By looking at the ones i have created, it should be quite straight forward to add a lot more.

**Comment by krescruz** [comment]
New components have been added @newmanw https://github.com/krescruz/angular-materialize/tree/master
