### ISSUE TITLE
How to select materialize work on ionic 

### ISSUE THREAD

**Issue by webinopoly** [krescruz/angular-materialize#100]
Hi to day i added your lib to ionic , but not work
Select materialize not change value when  select ? how to fix that?

**Comment by angelxmoreno** [comment]
You will have better luck asking in the Ionic [Slack channel](http://ionicworldwide.herokuapp.com/). As far as I know, you can not simply add a html ui framework and make it work in Ionic. Please have tried bootstrap and it simply does not work. I am under the impression materialize will also fail.

All that being said, you can use Angular+any html ui framework just using Cordova/Phonegap and not Ionic.

**Comment by webbiesdk** [comment]
I don't think anything will happen here. And i also agree that the Ionic guys are the ones to ask. 

So if this issue it to be reopened, we would need a lot more information (like a link to a page where the issue is present).
