### ISSUE TITLE
Select with data-icon attribute gets compiled only once.

### ISSUE THREAD

**Issue by JaffParker** [krescruz/angular-materialize#111]
I have the following code in my view:

```
<select name="community" id="community" material-select watch ng-model="vm.feed.community">
    <option value="" disabled selected>Choose your community</option>
    <option ng-repeat="group in vm.groups" data-icon="{{ group.image }}" value="{{ group.id }}">{{ group.name }}</option>
</select>
```

On the initial page load it compiles it with the icons, no problem. However, once I change a page and go back, the icons don't display anymore and the developer console shows `src="{{ group.image }}"`. So it means that it look to the model, it just takes the value and jams it into src.

**Comment by alexcaza** [comment]
The issue should be resolved, I've submitted a pull-request with the fix.

It was initializing the material select before Angular was done with it's digest cycle; which caused it to pass the un-evaluated expression to the `<img>` Materialize constructed.

It now waits until the digest cycle is done before initializing the select.
