### ISSUE TITLE
Is there a way to trigger a modal from controller?

### ISSUE THREAD

**Issue by sswainright** [krescruz/angular-materialize#114]
I need to be able to trigger a modal to show from controller code.  Is there a way to do that?  I only see link examples?  Much Thanks

**Comment by sgjackman** [comment]
I need this too. There has to be a way to do this right?

**Comment by webbiesdk** [comment]
If you look here: http://materializecss.com/modals.html

You can see that with Materialize, one can open a modal with the jQuery function `.openModal()`. 
There is however not currently implemented anything in angular-materialize that calls that function. 

Pull-requests are welcome, but until then, there is no pretty way to do it from your controller.

**Comment by sgjackman** [comment]
Hi, thanks for your reply. Yes I worked that out eventually, so now I have modals, but I can't see a way to hook into 'confirm' / 'cancel' buttons on these modals. Is there a good way to do this so that a modal can be used for confirmations?

**Comment by charleshimmer** [comment]
I needed the same functionally so I opened a pull request.

**Comment by webbiesdk** [comment]
The functionality is available after #128 was merged. 

So this issue is closed.
