### ISSUE TITLE
Can we have a time-picker?

### ISSUE THREAD

**Issue by crisryantan** [krescruz/angular-materialize#118]

**Comment by dhaval85** [comment]
+1 to this feature.

**Comment by webbiesdk** [comment]
+1 

If someone makes a pull-request, it will happen.
This addition to Materialize: https://github.com/chingyawhao/materialize-clockpicker could be used as a starting point. 

(further +1 will be deleted, and will be used to increment the +1 above)

**Comment by dhaval85** [comment]
I will check that out and see if I can do something and create a pull request.

**Comment by crisryantan** [comment]
thanks @dhaval85

**Comment by crisryantan** [comment]
a friend of mine made a clockpicker built on top of https://github.com/linagora/angular-clockpicker so that it would be compatible with angular-materialize: https://github.com/danswater/triton-materialize-clockpicker

**Comment by webbiesdk** [comment]
I implemented a wrapper for chingyawhao/materialize-clockpicker in the above commit. 

An example usage of it can be seen here: http://krescruz.github.io/angular-materialize/#input-clock
