### ISSUE TITLE
Can you add Accordion in this plugin/ framework

### ISSUE THREAD

**Issue by sibinx7** [krescruz/angular-materialize#12]
Sir
It would great if you add accordion in this package. One of application use materialize and angular. Ordinary materialize accordion is not working with Angular ( I don't know), Bootstrap accordion is very much different from materialize accordion. Can you please add this feature in new update 

Thanks in advance

**Comment by elboman** [comment]
I've created PR for the accordion, you can merge this commit if you need it 7ec4d5ec92329aada419ddd6d190283fb955d1c9

cheers

**Comment by webbiesdk** [comment]
Even if you don't use the code in the pull request, you can always use accordion like you would with materialize without Angular, if it is static content that isn't touched by Angular.

The [example page for this plugin](http://krescruz.github.io/angular-materialize/) actually uses this, the collapsible elements in the left side of the screen is implemented without using Angular in any way.

**Comment by webbiesdk** [comment]
The Accordion code from elboman is now merged, and an example has been added.
