### ISSUE TITLE
input-date not working with jquery 2.2.0

### ISSUE THREAD

**Issue by agustin107** [krescruz/angular-materialize#122]
Today I hadan issue with input-date, because when the user going to the datepicker, this not appeared.

Then I went to change the jquery file to jquery version 1.12.0, and this it´ s worked.

**Comment by nahueld** [comment]
thanks agustin! I had a hard time debugging this!!! I think the problems is in materialize

**Comment by webbiesdk** [comment]
I just tried to update to the newest version of jQuery (2.2.3), didn't get any error. 

If you still experience this, I can reopen the issue.
