### ISSUE TITLE
Not working the settings of input-date

### ISSUE THREAD

**Issue by agustin107** [krescruz/angular-materialize#123]
When I setting the options (months-full, months-short, etc), this not working and have default options.

**Comment by webbiesdk** [comment]
Here is the thing, I can't replicate the issue. I can set options such as months-full just fine (you can see an example of this in the index.html at the root of the repository). 

And in your "fix", you just remove the setTimeout function, and I'm having a real hard time seeing how that could fix the issue. (Adding setTimeout has fixed other issues in the past, so I'm really not keen on removing it). 

So before I'm going to merge #124, I need to see the issue that it fixes. You can upload it to jsfiddle, upload a zip file, send a link or whatever. I just need to see some code that works with the fix, and doesn't work without the fix.

**Comment by agustin107** [comment]
I don´t know how, but was resolved **automagically**!

Thanks for review this issue, and I going to close this issue and PR.
