### ISSUE TITLE
Add $timeout to Tabs

### ISSUE THREAD

**Issue by KOVIKO** [krescruz/angular-materialize#125]
I've noticed that [another issue](https://github.com/krescruz/angular-materialize/issues/80) made this suggestion, but it was for a strange reason. Personally, I found that the `$timeout` was necessary for allowing `ngClass` bindings to set the `active` class. Without it, the `active` class is applied after the `tabs` directive ran, meaning Materialize never sees it and makes the first item active.

It may be worth noting that I ran into this issue while using `uiRouter`.

**Comment by webbiesdk** [comment]
I can see that this would be an issue. And I can also see that adding `$timeout` would fix it. (So if you make a pull-request that adds `$timeout`, I would accept it). 

However, with this it is still not possible to dynamically change which tab is active, it still has to be fixed after the initialization. 

A better solution would be to add an `active` attribute, which would hold the index of the active tab, and the directive should then `$watch` that attribute, and make sure the tabs are updated to reflect it. 
I don't have the time to make that, but it would be awesome if someone did.

**Comment by akosbordas** [comment]
I was going to fix this issue when I saw that you already did it 2 days ago. :) Could you please release it? Beside this can you upgrade the version in the bower.json as well? (it's still in 0.1.3 but as I see 0.1.4 is available already)

**Comment by webbiesdk** [comment]
Yeah sure. 

I don't always remember to update the version number in the JSON files. 

I'll update some version numbers, make a release, and update npm and bower. 

And yeah, this issue is fixed by #152, so I'm closing this.

**Comment by webbiesdk** [comment]
Done, 0.1.5 is released, and both bower and npm should reflect this.

**Comment by akosbordas** [comment]
Thanks for the quick work! :)
