### ISSUE TITLE
No callback function when modal closes

### ISSUE THREAD

**Issue by hsoto92** [krescruz/angular-materialize#127]
I've bee looking for a callback function once the modal closes but I haven't found one. Is it not implemented on the directives?

**Comment by webbiesdk** [comment]
You are right, they aren't implemented here, yet. 

But it should be relatively straight-forward to do so, one just has to map the callbacks to the `ready` and `complete` options on the jQuery plugin. 
Documentation for the jQuery plugin can be found here: http://materializecss.com/modals.html

As always, pull-requests are welcome.
