### ISSUE TITLE
Directive scrollFire

### ISSUE THREAD

**Issue by Kroustille** [krescruz/angular-materialize#134]
Hello everyone, 

I need the scrollFire feature from the original materialize but when I went to the angular-materialize page, i saw that it isn't implemented.

Could you implement it?

Thank you !

**Comment by webbiesdk** [comment]
People generally don't implement anything in this library, unless they need it.

You need scrollFire, so you are welcome to implement it, and send a pull-request. 

That being said, the scrollFire API supplied by Materialize is ugly, so if you decide to implement this, I would suggest that you look at the Materialize.scrollFire code, and use that to make your own thing.

**Comment by webbiesdk** [comment]
Scrap that, I looked at the Materialize API, and decided I could do better. 

I got it working now, just need to make some documentation.

**Comment by webbiesdk** [comment]
Implemented, you can see it here: http://krescruz.github.io/angular-materialize/#scrollfire (clear cache if the link doesn't work).
