### ISSUE TITLE
Element recompilation may break 3rd party directives

### ISSUE THREAD

**Issue by svvac** [krescruz/angular-materialize#136]
Hi all.

I'm using a custom directives that heavily relies on `$compile` for its workings to dynamically add other directives to an element. However, when used in conjunction with the `dropdown` directive you supply, conditions (i.e. `ng-if`and kin) completely stopped working. When printing the condition in a template block, it evaluated to `true`, but the element wouldn't show up.

I finally found the culprit in the `$compile` call you do in the link phase: it forced the element to be recompiled in the isolated scope you use for the directive, hence breaking all references to my locals. Removing it did the trick.

But why do you recompile the element at all? All you need is to call the `.dropdown()` init function that setups the intended behavior, but since that is in jQuery world, it does not require Angular to recompile the element. Am I missing something, or is it useless indeed?

**Comment by webbiesdk** [comment]
I think you are right, the $compile shouldn't be needed for the dropdown to work. 

So I removed it, and nothing wen't wrong when i tried to test the dropdown. So I'm pushing it now.
