### ISSUE TITLE
tabulation on select

### ISSUE THREAD

**Issue by froobb** [krescruz/angular-materialize#137]
Hi all.

When I select a new value and press tab button, the focus is not on the next field. This is due because the function initSelect is call all the time in wacher at line 275 in angular-materialize.js . 

To resolve it, I have check if the change of model is due to the select, and if the changement is due to select, they are nothing to do.

I have replace this :
                            scope.$watch(attrs.ngModel, initSelect);

by :
                            scope.$watch(attrs.ngModel, function(newValue,oldValue){
                                if (newValue != element.parent().find("input").val())
                                    initSelect();
                            });

**Comment by webbiesdk** [comment]
If you make a pull-request, I can test it, and you get to be on the list of contributors.

**Comment by webbiesdk** [comment]
I believe this was fixed by #143.
