### ISSUE TITLE
Changing view breaks directive

### ISSUE THREAD

**Issue by j-quelly** [krescruz/angular-materialize#138]
I'm using the tabs directive inside a view.  When it's initially loaded the directive works just fine, however when I change the view it appears as though the tabs break.

For example:
1. I'm located at /#/
2. I click an element and change the path to /#/path/123.  The view changes and the tabs work just fine.
3. I click another element and the view reloads to /#/path/124 but the tabs are broken, the content for both tabs are displaying.

**Comment by webbiesdk** [comment]
In the index.html example, I have a button that toggles visibility, exactly to catch issues like the one you describe. 

Using that I cannot replicate the issue you are describing. 

Could you create a small example, on something like JSFiddle, that demonstrates the issue?

**Comment by j-quelly** [comment]
It appears as though I was using this incorrectly.  I've since added the ng-if and the tabs work across either view.

However, this presents another **minor** issues where the indicator is not present on load and only appears after a tab has been clicked.

Any suggestions?

**Comment by webbiesdk** [comment]
I don't think you need the ng-if for your use-case, since you just need to show it when the right view is being displayed. 

So again, we'll need you to upload an example that demonstrates the issue somewhere, or we have no chance of fixing the issue.

**Comment by j-quelly** [comment]
For me the indicator seems to appear at random.

Update:

I've since discovered this issue is caused by the ng-hide directive.  It seems as though the calculation for the indicator is run before the ng-hide directive displays the tabs to the screen.  This is likely more of an issue with materialize than with this dependency.  My fix is as follows:

Change materialize.js from:
`if ($this.is(":visible")) {
                    $indicator.css({ "right": $tabs_width - (($index + 1) * $tab_width) });
                    $indicator.css({ "left": $index * $tab_width });
                }`

To:
`if ($this.is(":visible")) {
                    $indicator.css({ "right": $tabs_width - (($index + 1) * $tab_width) });
                    $indicator.css({ "left": $index * $tab_width });
                } else {
                    setTimeout(function() {
                        $tabs_width = $this.width(),
                            $tab_width = $this.find('li').first().outerWidth()
                        $indicator.css({ "right": $tabs_width - (($index + 1) * $tab_width) });
                        $indicator.css({ "left": $index * $tab_width });
                    }, 100)
                }`

If anyone has any better suggestions please let me know.
