### ISSUE TITLE
JQuery dependency

### ISSUE THREAD

**Issue by chamindu** [krescruz/angular-materialize#14]
I found out that this module needs JQuery the hard way. Can we remove the JQuery dependency?

**Comment by elboman** [comment]
This modules is based on Materilize which depends on jQuery. The directives included in this module make sure that components initialized in Materialize.js on document ready (mainly) are handled by Angular in the right way. It's not a complete rewrite of the javascript of Materialize (like ui.bootstrap is for bootstrap). So it's not possible to remove jQuery as a dependency..

**Comment by webbiesdk** [comment]
alboman is right, we can't remove jQuery, because we depend on Materialize.js, which depends on jQuery.

But it is not the first time this question has been asked, so i added a little about section, 9dbd77d94142821c04bde783760c057e395b8d2c that should explain it to others.
