### ISSUE TITLE
Do I need to add the original materialize library to use this one?

### ISSUE THREAD

**Issue by johhansantana** [krescruz/angular-materialize#144]
I'm currently using [https://github.com/poetic/meteor-materialize-scss](url) to add materializecss with sass  variables.

Would using this `angular-materialize` affect this package or am I safe to use `angular-materialize` with the official materialize, or should I just use `angular-materialize` alone?

If I have to use this one alone, is there a way to setup my colors, I currently have them like this:

```
$primary-color-dark:   #00796B;
$primary-color:        #009688;
$primary-color-light:  #B2DFDB;
$primary-color-text:   #FFFFFF;
$accent-color:         #CDDC39;
$primary-text-color:   #212121;
$secondary-text-color: #727272;
$divider-color:        #B6B6B6;
```

Thanks!

**Comment by webbiesdk** [comment]
(Note to self: update the readme)

It sound like you think that this package is independent of Materialize, it isn't. 
It is an addition, you still need everything in the "original" Materialize in order for this library to work. 

In particular, this project does nothing with the CSS, meaning that you can use saas just like you would if you didn't add the angular part. 

So i don't think there is any problem with using the saas package you are linking to (without having looked at it). 

A lot of people have had problems with which order to include the different JavaScript files, i recommend you look at the index.html in the root of this repository, to see how to setup the JavaScript dependencies.
