### ISSUE TITLE
Open datepicker from button..

### ISSUE THREAD

**Issue by gfamorimo** [krescruz/angular-materialize#146]
I've tried fire the datepicker from icon but don't work...
When I use the code from console, the datepicker open.
Someone had tried this?

```
return {
      restrict: 'E',
      scope: {
        idDatepicker: '@'
      },
      template: '<ng-md-icon id="btn{{idDatepicker}}" icon="event"></ng-md-icon>',
      link: function (scope, element, attrs) {
        $('#btn'+scope.idDatepicker).click(function(event){
          event.stopPropagation();
          $('#'+scope.idDatepicker).first().pickadate("picker").open();
        });
      }
    };
```

**Comment by webbiesdk** [comment]
In order for me to have any idea of how to help you, I need some more code. 

And the easiest way to do that, is for you to upload what you have done so far, to some page, so i can actually see the issue. 

Closed until then.
