### ISSUE TITLE
Modal Open Callback

### ISSUE THREAD

**Issue by m-gv** [krescruz/angular-materialize#149]
I am using the modal tag callback system as made visible in the documentation:

```
<a class="btn ng-isolate-scope" href="#demoModal" modal="" ready="readyCallback" complete="completeCallback" open="openModal"><span class="ng-scope">Show Modal</span></a>
```

The ready and complete callbacks trigger my functions just fine, however the open callback does not seem to trigger my function.

If this is not the intended purpose of the callback, could you please outline what it is meant to do?

(in the meantime I will be using ng-click to trigger my open method)

Thanks!

**Comment by webbiesdk** [comment]
`open` is not a callback, it is a boolean variable that if set to `true`, opens the modal. 

You can see that in the index.html file where the button `<a class='btn' ng-click="openModal = true">Open from controller</a>` opens the modal when clicked. 

We should properly make the documentation clearer about this.

**Comment by m-gv** [comment]
Alright, thank you for clearing that up
