### ISSUE TITLE
how do I use this

### ISSUE THREAD

**Issue by ekarudianto** [krescruz/angular-materialize#15]
I've been using materialize as my css framework for my angularjs project... and then I found this.. could you tell me how to use it ?

**Comment by webbiesdk** [comment]
You can see a simple example on the root of the repository, in the index.html file. 

But all you really have to do is make sure that the following scripts are loaded. 
- jQuery
- angular
- materialize.js (the JavaScript used by the materialize framework)
- angular-materialize (this library). 

And then just use the directives as explained here: 
http://krescruz.github.io/angular-materialize/

**Comment by ekarudianto** [comment]
have you test this using Gruntjs and Yeoman ? @webbiesdk

**Comment by webbiesdk** [comment]
nope

**Comment by ataurrahim** [comment]
What version of AngularJS is required?

**Comment by webbiesdk** [comment]
In the example page, 1.3.5 is used, but it might work with a lower version of AngularJS. 

I havn't tested other version, so i suggest you to just try with the version you have, and see if it works.

**Comment by ataurrahim** [comment]
Tried it with 1.2.16, things seems to be working.

**Comment by autoferrit** [comment]
Is this mutually exclusive to the `angular-material` plugin? I was wondering if I also needed that package for anything or if this one completely replaces it.

**Comment by webbiesdk** [comment]
Angular-material is a different plugin, and is not needed for angular-materialize to work.

**Comment by erperejildo** [comment]
Please, edit the readme file with this information

**Comment by webbiesdk** [comment]
@erperejildo done.
