### ISSUE TITLE
getting error while using Select 

### ISSUE THREAD

**Issue by SUVADEEP** [krescruz/angular-materialize#151]
error :  element.material_select is not a function
I looked into the directive 'materialSelect' and consoled the element obj , it seems getting the array value but somehow couldnot recognize the jquery function.

And point to mention I have multiple select in one form

**Comment by webbiesdk** [comment]
Sounds like you didn't include Materialize.js, you can see the index.html file for what JavaScripts to include in which order. 

If you want further help, link to a page where the issue is present.
