### ISSUE TITLE
tabs li ng-if

### ISSUE THREAD

**Issue by NatsuOnFire** [krescruz/angular-materialize#152]
The tabs directive mismanaging the indicator when I put the ng-if on li.

**Comment by webbiesdk** [comment]
Could you show an example, post a link to a page where the issue is present, or create an example on a page like JSFiddle?

**Comment by NatsuOnFire** [comment]
Here is the link but I can  not succeed in doing run jsFiddle with angular and angular-materialize :
http://jsfiddle.net/wevg7qwr/3/

**Comment by webbiesdk** [comment]
Yeah it didn't work because: 
1. You didn't include all dependencies (forgot jQuery)
2. Including an external resource from raw.github.. doesn't work, by design from github. 

I got your thing to work on another JSFiddle: http://jsfiddle.net/rdevvr7u/
I had to change "tabs" to "$scope.tabs" in some places for it to work. 

And I don't see anything not working.

**Comment by NatsuOnFire** [comment]
Ok, this is what I want operation. But taking your code, I was able to reproduce the bug that I meet in my application: http://jsfiddle.net/wevg7qwr/5/
The indicator is not working properly.

The problem is the order of the libraries, I import materialize.js before angular.js. Conversely, it works.

**Comment by NatsuOnFire** [comment]
In my application, it still does not work. The indicator does not appear. When I click the first time, it appears taking 100% of the width and after the second click, it's good.

Here are all the scripts that I use :

```
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/angular-animate/angular-animate.js"></script>
<script src="bower_components/materialize/bin/materialize.js"></script>
<script src="bower_components/angular-materialize/src/angular-materialize.js"></script>
<script src="bower_components/angular-cookies/angular-cookies.js"></script>
<script src="bower_components/angular-resource/angular-resource.js"></script>
<script src="bower_components/angular-route/angular-route.js"></script>
<script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
<script src="bower_components/angular-touch/angular-touch.js"></script>
<script src="bower_components/angular-paging/dist/paging.js"></script>
<script src="bower_components/jquery-mousewheel/jquery.mousewheel.js"></script>
<script src="bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.js"></script>
<script src="bower_components/ng-scrollbars/dist/scrollbars.min.js"></script>
```

Here are some screens of the problem :
http://www.hostingpics.net/viewer.php?id=783516tabs1.png
first click : http://www.hostingpics.net/viewer.php?id=612710tabs2.png
second click : http://www.hostingpics.net/viewer.php?id=747020tabs3.png

**Comment by NatsuOnFire** [comment]
By adding a $timeout, it works. So the problem is that the call to the tabs is too fast compared to the display.

```
angular.module("ui.materialize.tabs", [])
    .directive("tabs", ["$timeout", function($timeout){
      return {
        link: function (scope, element, attrs) {
          $timeout(function() {
            element.tabs();
          });
        }
      };
    }]);
```

Will you have another solution in order not to change angular-materialize.js directly?

**Comment by webbiesdk** [comment]
> Here are some screens of the problem :
> http://www.hostingpics.net/viewer.php?id=783516tabs1.png
> first click : http://www.hostingpics.net/viewer.php?id=612710tabs2.png
> second click : http://www.hostingpics.net/viewer.php?id=747020tabs3.png

I can't get the links to work, could you try to host the images somewhere else, like imgur.com?

**Comment by NatsuOnFire** [comment]
Of course ^^
http://imgur.com/fmVcZ8E
first click : http://imgur.com/3vYFyJz
second click : http://imgur.com/QbfOPMm

**Comment by webbiesdk** [comment]
I think the timeout is the right thing to do, since the problem seems to be that the materialize-code sees all the tabs, before angular hides the non-existing ng-ifs. 

So we have to postpone the tabs initialization until after angular has rendered, and the way to do that seems to be adding a $timeout (as an example, see this: http://stackoverflow.com/questions/11125078/is-there-a-post-render-callback-for-angular-js-directive)

**Comment by NatsuOnFire** [comment]
Ok, I'll do it in this case. Thank you for your help.

**Comment by webbiesdk** [comment]
I added the $timeout thing in the above commit.

**Comment by NatsuOnFire** [comment]
Perfect, thank you again for your help. Only wait the release now ^_^
