### ISSUE TITLE
Pagination - inconsisent <next> and <last> buttons

### ISSUE THREAD

**Issue by jacek213** [krescruz/angular-materialize#153]
Hello,

In native materialize buttons for first, prev, next, last page are built with material fonts: 
http://materializecss.com/pagination.html

In this lib there are built with <<, <, >, >>. It doesn't look really nice.

**Comment by webbiesdk** [comment]
That could happen, and the chevron_left/right seems to be good for prev/next. 

But i cannot find any icons that would be good as last/first, do you have any candidates?

**Comment by jacek213** [comment]
Thanks for the quick response :) 

What do you think about https://design.google.com/icons/#ic_last_page?

**Comment by webbiesdk** [comment]
Turned out to be a little more complicated than just copy-pasting some icon HTML. But now it is done.

**Comment by jacek213** [comment]
Awesome, thanks a lot :)

**Comment by jacek213** [comment]
BTW when are you planning to make a new release including this feature?

**Comment by webbiesdk** [comment]
Now

**Comment by jacek213** [comment]
Thanks for the quick release. However either there were some changes in your API and I need to update my code or there's a regression.

In my directive call I got `pagination-action="usersCtrl.onPageChange(page)"`

 When I click on next button ">" everything works as expected and the `onPageChange` function receives `page == 2` argument. However when I click on certain page number instead, I get `page = TrustedValueHolderType {}` as an argument instead of string with page number and therefore page would not change.

**Comment by webbiesdk** [comment]
No idea what is happening, because it works here. 

Our demo-page: http://krescruz.github.io/angular-materialize/#pagination is setup to print every page that one switches to, and that works just fine, nomatter which button (or number) you press. 

So I'm going to need an example page before I can proceed. Lucky for you, creating an example on a page like JSFiddle has just gotten easier, since this library was added to cdnjs. 
(You can look at the [getting-started](http://krescruz.github.io/angular-materialize/#getting-started) to see what to include. )

**Comment by jacek213** [comment]
Ok, I got this: http://jsfiddle.net/Lvc0u55v/4071/

So everything is clear now. Check the code where debugger is placed, `page` returns an object (probably it was run through `$sce`) and previously it was simply a string. To get a string with page number one need to do `page.$$unwrapTrustedValue()`. My problem was a was passing a raw page object to my API and got first page each time. Might be worth documenting.

**Comment by jacek213** [comment]
Actually, to support both options that is prev / next buttons and page numbers something like this has to be done:

```
function onPageChange(page) {
  var requestedPage;

  if (typeof page === "object") {
    requestedPage = page.$$unwrapTrustedValue();
  } else {
    requestedPage = page;
  }

  // safely pass requestedPage as `page` param to ur backend now

}
```

**Comment by webbiesdk** [comment]
Oh, now i see. The reason why i thought it worked, is that the `.valueOf()` still returns the original value. (`.valueOf` is implicitly called when doing string-concatination, which i did in index.html)

So if you want a simpler fix for the current version, just call `.valueOf()` on `page`. 

I'm making a fix now (probably calling `.valueOf()`) and pushing it (and I get a chance to test out how fast cdnjs updates).
