### ISSUE TITLE
Select in Angular-Materialize don't show me, appear in display:none

### ISSUE THREAD

**Issue by gomezv9** [krescruz/angular-materialize#156]
Hi

I have a problem with the Angular-Materialize Select in my project.

The problem is that the select show me in "display:none", I think that it haven´t been execute very good in the javascript or I don´t know.

This is my Select:

```
<div input-field>
    <select ng-model="selected_state" ng-change="getArrayCities(selected_state)">
         <option value="" disabled selected>Choose a state</option>
         <option ng-repeat="st in usa track by $index" value="{{st}}" >{{st.name}}</option>
    </select>
</div>
```

But if I put the class:"browser-default", it show without the Angular-Materialize effect but it work perfect, like this:

```
<div input-field>
    <select ng-model="selected_state" class="browser-default" ng-change="getArrayCities(selected_state)">
        <option value="" disabled selected>Choose a state</option>
        <option ng-repeat="st in usa track by $index" value="{{st}}" >{{st.name}}</option>
    </select>
</div>
```

I don't know why this happend.

Any help ?

**Comment by webbiesdk** [comment]
You didn't add the `material-select` attribute. This is how it looks with `material-select` added: 

```
<div input-field>
    <select ng-model="selected_state" ng-change="getArrayCities(selected_state)" material-select>
         <option value="" disabled selected>Choose a state</option>
         <option ng-repeat="st in usa track by $index" value="{{st}}" >{{st.name}}</option>
    </select>
</div>
```

Without the `material-select` attribute, the Angular code doesn't kick in.

**Comment by gomezv9** [comment]
thank, even so it is still not working, the select appear in display:none

**Comment by johhansantana** [comment]
I'm having this issue as well but only when I deploy on heroku, locally it works fine.

Here's how it looks when deployed:
![screenshot from 2016-06-21 12 03 26](https://cloud.githubusercontent.com/assets/9933887/16236949/369df24e-37a8-11e6-8503-66d8c88251e3.png)

and here's how it looks locally:
![screenshot from 2016-06-21 12 03 43](https://cloud.githubusercontent.com/assets/9933887/16236958/3ebec386-37a8-11e6-9dc2-08b564d08409.png)

Although I have the `watch` alongside `material-select` like this `material-select watch` as attributes.

**EDIT**
After going to the console and typing this `$('select').material_select();` the select appeared and it's working. A quick fix for this might be to create a directive that runs this code in the select (which is what's suppose to happen when you have `material-select watch` I'm guessing?).

**Comment by webbiesdk** [comment]
The last comment sounds like a missing CSS dependency.

But I cannot help any further unless you give me a link I can click on, where the page that it leads to shows the error.
