### ISSUE TITLE
DatePicker doesn't show on Edge browser, scrolls the page down on IE and Edge

### ISSUE THREAD

**Issue by beneficialmedia** [krescruz/angular-materialize#157]
I'm doing a compatibility test pass and cannot get the angular-materialize datepicker to work on IE and Edge. Any workarounds here?

**Comment by beneficialmedia** [comment]
Any chance we could get help on this?

**Comment by webbiesdk** [comment]
I can confirm that it happens. But i have no idea why it happens. 
I might look at it at a later time, but don't expect anything soon. 

You could also try to fix it yourself, and then send a pull-request if you manage to fix it.

**Comment by webbiesdk** [comment]
Apparently IE and Edge doesn't handle it well when the popup has a parent which is not next to the input. 

Fixed.
