### ISSUE TITLE
Select in display none, bug ??

### ISSUE THREAD

**Issue by gomezv9** [krescruz/angular-materialize#159]
Hi

I have a problem with the Angular-Materialize Select in my project.

The problem is that the select show me in "display:none", I think that it haven´t been execute very good in the javascript or I don´t know.

This is my Select:

```
<div input-field>
    <select ng-model="selected_state" ng-change="getArrayCities(selected_state)" material-select watch>
         <option value="" disabled selected>Choose a state</option>
         <option ng-repeat="st in usa track by $index" value="{{st}}" >{{st.name}}</option>
    </select>
</div>
```

But if I put the class:"browser-default", it show without the Angular-Materialize effect but it work perfect, like this:

```
<div input-field>
    <select ng-model="selected_state" class="browser-default" ng-change="getArrayCities(selected_state)">
        <option value="" disabled selected>Choose a state</option>
        <option ng-repeat="st in usa track by $index" value="{{st}}" >{{st.name}}</option>
    </select>
</div>
```

I don't know why this happend.

Any help ?

**Comment by webbiesdk** [comment]
You didn't have to open a new issue, I would have re-opened the old one. But I'll continue here. 

An issue of this type sounds like a dependency issue. 
If you look here: http://krescruz.github.io/angular-materialize/#getting-started
There is a list of JavaScript and CSS files that are included in the `head`, make sure you include ALL of those. 

Can you open the JavaScript console, and say what gets printed there? 

If none of that yeilds anything, then I'll need an example i can see myself, so upload an example on a page like JSFiddle. 
(You can use this one: http://krescruz.github.io/angular-materialize/#getting-started as a starting point).

**Comment by webbiesdk** [comment]
Closed until more information is provided.
