### ISSUE TITLE
tabs directive does not work when tab content is loaded dynamically

### ISSUE THREAD

**Issue by akosbordas** [krescruz/angular-materialize#162]
When you try to use ng-include to load tab content you can run into a strange bug. If ng-include loads the content later than the tabs have been initialized then multiple tab content can be visible for the first time when the page appears. It can happen with any other dynamic content loading. 
I investigated a bit the possible solutions. I suggest to add a 'reload' property to the directive which can be triggered from outside. So that it is possible to reload the tabs again when the sub-pages are ready.

Ps.: maybe it would be a better solution to make available the jQuery's tabs API, but the guys from materialize have overridden the original function, so it has limited possibilities.

**Comment by webbiesdk** [comment]
Fixed by #163, right?

**Comment by akosbordas** [comment]
yep. :) can you make a new release?

**Comment by webbiesdk** [comment]
Done.

**Comment by akosbordas** [comment]
thanks
