### ISSUE TITLE
Is angular-materialize still being maintained? 

### ISSUE THREAD

**Issue by hsoto92** [krescruz/angular-materialize#164]
I'm about to start a big project, and I want to know if angular-materialize is still being maintained by @krescruz? As I would love to choose this as my front-end UI framework.

**Comment by webbiesdk** [comment]
@krescruz isn't doing much around here, but I'm around. 

Sometimes answers only come after a week or two (or a month if I'm busy), but the project is very much alive. 

Also, the quickest way to get something fixed, is to fix it yourself and send a pull-request.
