### ISSUE TITLE
Slider is not working

### ISSUE THREAD

**Issue by thierryskoda** [krescruz/angular-materialize#166]
Hi, I tried to copy and paste the example for the slider in my code and it's not working. I have no error, but the image doesn't appear (opacity 0) and the transition are never triggered (maybe I don't see them because I can't see any images). 

PS: All the other components are working.

Thank you very much for any help!

**Comment by webbiesdk** [comment]
I just put up a issue-template: https://github.com/krescruz/angular-materialize/blob/master/.github/ISSUE_TEMPLATE.md

Read it, then submit a new issue.
