### ISSUE TITLE
input 2 way binding

### ISSUE THREAD

**Issue by nikhilrayaprolu** [krescruz/angular-materialize#168]
http://jsfiddle.net/f0rb9wjy/

why is my variable {{Questionnuber}}not changing its value in parent scope

**Comment by webbiesdk** [comment]
http://stackoverflow.com/questions/17606936/why-dont-the-angularjs-docs-use-a-dot-in-the-model-directive

TL;DR: Have an object instead, with a field, which contains the actual value. Because scope inheritance.
