### ISSUE TITLE
Pushpin flashes

### ISSUE THREAD

**Issue by famagusta** [krescruz/angular-materialize#169]
The pushpin directives cause it to flash and turn up near top of page where it is not supposed to.

Below is my code snippet

 <div class="col s12 m3">
                    <div class="card dash_graphcard" pushpin pushpin-top="100" pushpin-offset="0" pushpin-bottom="Infinity">
...

**Comment by webbiesdk** [comment]
There is no code snippet

**Comment by webbiesdk** [comment]
There is still no code snippet.
