### ISSUE TITLE
need the Collapsible component

### ISSUE THREAD

**Issue by Windfarer** [krescruz/angular-materialize#17]
i want to use [this](http://materializecss.com/collapsible.html) component in angular project.

**Comment by webbiesdk** [comment]
We actually have that, the github.io page just didn't reflect it. (Guessing you looked there).  
So i synchronized the master branch with the github.io page, and now the documentation for the collapsible directive is visible on github.io

http://krescruz.github.io/angular-materialize/#collapsible

If the link doesn't take you to documentation about collapsible, try to clear the browser cache.
