### ISSUE TITLE
ng-show issue

### ISSUE THREAD

**Issue by YairHadari** [krescruz/angular-materialize#170]
Hi,

I"m using the materializecss library for javascript and enjoying it a lot - BIG thanks!!!

Recently I started to work with Angular JS.

I"m attaching the following libraries to my file:
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

<script type="text/javascript" src="https://code.jquery.com/jquery-3.0.0.min.js"></script>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular-materialize/0.1.9/angular-materialize.min.js"></script> 

When using `<span class="help-block" ng-show="errorUrl">{{ errorUrl }}</span>` with Bootstrap, an error message is displayed as expected.

When using same file with the materialize.min.js and angular-materialize.min.js I can see on the browser `{{ errorUrl }}` when the application is loaded.
It seems that ng-show is not functioning well with the angular-materialize.min.js library.

Thanks again,
Yair

**Comment by webbiesdk** [comment]
I just tried to use `ng-show` with angular-materialize. And it worked perfectly, the problem is something else on your page. 

I suggest reading the bottom of this: https://github.com/krescruz/angular-materialize/blob/master/.github/ISSUE_TEMPLATE.md
And maybe posting a new issue.

**Comment by YairHadari** [comment]
When I"m working with ajax.googleapis.com/ajax/libs/angularjs/**1.5.5**/angular.min.js it didn't work.
Replacing the library to ajax.googleapis.com/ajax/libs/angularjs/**1.2.0**/angular.min.js did the work.

Thanks
