### ISSUE TITLE
Input field doesn't get focus because of floating label / placeholder

### ISSUE THREAD

**Issue by danivaan** [krescruz/angular-materialize#172]
On an empty input field, the floating label (as placeholder) blocks clicks. When clicking on the label, the focus is not transferred to the input field. If the click point is outside the label area, the focus works as expected.

Tested on Chrome 51.0.
## Steps to reproduce
- Open page http://krescruz.github.io/angular-materialize/#input-field
- Empty the input field.
- Click outside the input field so that the floating label appears as placeholder.
- Click on the input field where the placeholder label is.
## What exactly is supposed to happen

The focus should go to the input field and user should be able to start typing.
## What exactly does happen

The placeholder text gets the click and the focus never goes to the input field.
## A link to a page clearly demonstrating the issue

http://krescruz.github.io/angular-materialize/#input-field

**Comment by webbiesdk** [comment]
Can reproduce, will look at it later.

**Comment by rockzgarf** [comment]
I think the floating **label** should have "**for**" attribute with the unique name same as the "**id**" attribute on the **input** to get the input focused when the floating label clicked.

**Comment by webbiesdk** [comment]
Thanks @rockzgarf that was exactly what was needed. 

But I think that it shouldn't have to be that way, so I added some code that puts in the `id` `for` pair, if it isn't there already. 
Thereby fixing the issue.
