### ISSUE TITLE
Add autocomplete directive

### ISSUE THREAD

**Issue by diogodomanski** [krescruz/angular-materialize#18]

**Comment by webbiesdk** [comment]
This repo consists of directives for the Materialize CSS framework (https://github.com/Dogfalo/materialize). 

There are no autocomplete in the Materialize CSS framework, so there wont be one in this. 

You could change to Angulars material implementation, they have an autocomplete implementation. 
https://material.angularjs.org/#/demo/material.components.autocomplete
