### ISSUE TITLE
Changes to model in ready function are not applied in the displayed modal

### ISSUE THREAD

**Issue by harawata** [krescruz/angular-materialize#184]
Changes to model in ready function are not applied in the displayed modal.
Here is a demo:
http://codepen.io/anon/pen/wWbVWX

Modifying [this line](https://github.com/krescruz/angular-materialize/blob/80e359af3762efabc705653306f6271ac33a4452/src/angular-materialize.js#L1083) as follows seems to fix the issue.

``` patch
                         var ready = function() {
-                          angular.isFunction(scope.ready) && scope.$eval(scope.ready());
+                          angular.isFunction(scope.ready) && scope.$apply(scope.ready);
                           // Need to keep open boolean in sync.
                           scope.open = true;
```

**Comment by webbiesdk** [comment]
Right you are, I made the same change with the `complete` as well.

**Comment by harawata** [comment]
Thank you for the fix, @webbiesdk !
Applying the change to `complete` seems to be a good idea, but [this line](https://github.com/krescruz/angular-materialize/blob/702b702e84b690de202c9c0c65582dcdb47c827d/src/angular-materialize.js#L1086) might become redundant.

**Comment by webbiesdk** [comment]
I think it is still needed, because of the `scope.open = false;` right above it.

**Comment by harawata** [comment]
You may be right. (I'm still new to this ;D)
Thanks for the comment anyway!
