### ISSUE TITLE
Datepicker's firstDay attribute doesn't work

### ISSUE THREAD

**Issue by chosa91** [krescruz/angular-materialize#187]
## Describe the error in 1 sentence

Datepicker's firstDay attribute doesn't work. I setted it in the $scope.firstDay and in the element firstDay="{{ firstDay }}", but it's doesn't work.

**Comment by webbiesdk** [comment]
You can see in the documentation that I just pushed how `first-day` is set, like this: `first-day="1"`. 
Valid inputs are 0 (for sunday) or 1 (for monday).
