### ISSUE TITLE
Slider within ng-repeat to generate images not working

### ISSUE THREAD

**Issue by rauldearaujo** [krescruz/angular-materialize#189]
In this case, the slider shows a grey background.

```
<div class="slider" slider>
      <ul class="slides">
        <div ng-repeat="image in images">
            <li>
              <img src="{{image}}">
            </li>
        </div>
      </ul>
  </div>
```

**Comment by webbiesdk** [comment]
You have `div`'s under your `ul`. Try putting the `ng-repeat` in the `li` instead, and get rid of the div between the `ul` and the `li`, because that might be confusing for the script.

**Comment by rauldearaujo** [comment]
Very good! Thaks! :D
