### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by ArsLucidum** [krescruz/angular-materialize#19]
Hi, I'm trying to implement pagination in my site but it just won't work in chrome. It appears, but it doesn't call the function defined in pagination-action (it does work on firefox). The worst thing is, I took a look at the sample code in your page and that sample is supposed to create toasts but they don't appear either (no toast is working in the sample page in fact). Could you take a look at it please?

**Comment by webbiesdk** [comment]
Cannot explain the pagination for now. 

But toast is broken because i didn't test it when i updated the materialize JavaScript (where the global toast function changed to Materialize.toast). 
I'll fix the toast later today. 

If that doesn't fix your issue, then I'll need a link or something so we can see your particular issue.

**Comment by webbiesdk** [comment]
Okay, i fixed the toast thing. 

But I don't know what to do with pagination. Just tried our example page in Chrome, Firefox and IE. Seems to be working.

**Comment by ArsLucidum** [comment]
Thanks for fixing the toast, and sorry about the pagination, it turned out to be my problem (chrome was reloading from cache and not showing last changes I did).

BTW, unrelated issue, but is it necessary to have ui.materialize in the module as a dependency for pagination to work? the sample wasn't clear about it.

**Comment by webbiesdk** [comment]
Yes it is. 

ui.materialize includes all the directives, if you don't include the ui.materialize module, Angular won't know how to resolve the materialize directives in your app.
