### ISSUE TITLE
Problem if I use atribute modal with tooltiped

### ISSUE THREAD

**Issue by Frauches** [krescruz/angular-materialize#190]
## Describe the error in 1 sentence

An error happens if a build something like an anchor or button using modal and tooltipped together
## Steps to reproduce

In this case, if I am using modal and tooltipped together. It generates an error on browser's console.

For instance:
<a class="btn-floating yellow darken-2 marginButton" 
     tooltipped
     modal
     data-position="top" 
     data-delay="50" 
    data-tooltip="Editar">
    <i class="material-icons">mode_edit</i>
</a>
## What exactly is supposed to happen

...
## What exactly does happens

The following error occurs on browser's console.

angular.min.js:118 Error: [$compile:multidir] http://errors.angularjs.org/1.5.8/$compile/multidir?p0=modal&p1=&p2=tooltip…ition%3D%22top%22%20data-delay%3D%2250%22%20data-tooltip%3D%22Editar%22%3E
    at Error (native)

**Comment by webbiesdk** [comment]
The problem was [insert technical description with [link to documentation](https://docs.angularjs.org/error/$compile/multidir)], but the tooltips directive didn't actually need its own scope, since it never uses it. So I removed it, and your use-case works now.
