### ISSUE TITLE
import this directive can not work?

### ISSUE THREAD

**Issue by strongant** [krescruz/angular-materialize#194]
js

```
 var mainApplicationModule = angular.module(
        mainApplicationModuleName, ['app.config', 'ngResource', 'ngRoute', 'ui.materialize','main'
        ]);
```

html

<a tooltipped data-position="bottom" data-delay="50" data-tooltip="test">
                    <i class="material-icons" ng-class='commentHate'>insert_comment</i>
</a>

the tooltipped  can not work?

**Comment by webbiesdk** [comment]
> If no link to a page where the issue is present is provided, expect the issue to be closed.
