### ISSUE TITLE
your angular-materialize/src/angular-materialize.js have a explain error!

### ISSUE THREAD

**Issue by strongant** [krescruz/angular-materialize#195]
In angular-materialize/src/angular-materialize.js line 5 to 7 :

```
 /*     example usage:
     <div scroll-fire="func('Scrolled', 2000)" ></scroll-fire>
     */
```

I think you should update this block,such as:

```
 /*     example usage:
     <div scroll-fire="func('Scrolled', 2000)"></div>
     */
```

**Comment by webbiesdk** [comment]
Right you are, a while back the start tag was also scroll-fire, but apparently the end tag wasn't fixed when the start tag was updated.
