### ISSUE TITLE
Text Fields Align Improperly on IOS

### ISSUE THREAD

**Issue by ChooseDews** [krescruz/angular-materialize#197]
## Issue

On IOS text fields display incorrectly, with the label over to the right of the text feild.
## Steps to reproduce

1) Open a page in chrome with a text fields
2) Compare page on IOS

The expected results would be both pages loading the same.

Below is an identical page loaded in chrome (left) &  IOS sim (right)

<img width="1019" alt="issueios" src="https://cloud.githubusercontent.com/assets/13653568/19527510/4d47bce4-95f6-11e6-83de-fc1b25507098.png">

If you want to check out the code yourself https://admin.dev.catchthefever.com/#/customer

**Comment by webbiesdk** [comment]
1. This sounds like an issue with Materialize, see if you can recreate this without angular-materialize. And if you can submit an issue with them: https://github.com/Dogfalo/materialize
2. I do not have an IOS device, or a Mac, and I therefore don't know how to replicate the issue.

**Comment by ChooseDews** [comment]
Just tested it out, something in the newest materialize update is the issue. v0.97.6 allows fields to work as expected.
