### ISSUE TITLE
ui.materialize.inputfield linking

### ISSUE THREAD

**Issue by nadar** [krescruz/angular-materialize#20]
Hi! First of all, thanks for the great work!

can you explain me the behavior of the linking function

``` js
link: function (scope, element) {
                    $timeout(function () {
                        angular.element(element).find("input").change();
                    });
                },
```

inside the inputField directive? if i wrap your directive inside another directive template, the parent controller scope variable will not set anymore. Stupid Example:

``` js
app.directive('customInputText', function(){
    return {
        restrict : 'E',
        scope : {
            'model' : '=',
            'label' : '@label'
        },
        template : function() {
            return '<input-field><input ng-model="model" type="text" /><label>{{label}}</label></input-field>';
        }
    }
});
```

if a controller now sets the scope variable model to "foobar" the value will not assigned. Looks like the two-way databinding does not work anymore. if we remove the linking function from your inputField directive, everything works fine. Can you explain me this (expected?) behavior?

**Comment by webbiesdk** [comment]
The linking function doesn't really do a lot, its only purpose is to trigger change, which triggers the jQuery code made by materialize, which makes sure that the placeholder text is placed correct. 

So i don't think its the linking function that is causing the problems. 

I am by no means an Angular expert, and when making the directive, i tried to make with nested angular content, that is why transclude is set to true, and there is the ng-transclude attribute in the template. 

What i'm saying is that i don't know how to fix your problem, but i don't think its the linking function you should look at.

**Comment by nadar** [comment]
It seems to be wide known "problem" losing the scope values inside transclude content. I made some examples: https://github.com/nadar/ng-tests. Thanks for your answer, i guess you can close this issue.

regards
