### ISSUE TITLE
No easy way to pass title to select options, or to have labels.

### ISSUE THREAD

**Issue by JCron245** [krescruz/angular-materialize#201]
## Describe the error in 1 sentence
When using select the options require a title attribute or label otherwise are un-accessible to blind or limited mobility users.
...

## Steps to reproduce
Just make a select menu and once getting displayed you can see the <select><options> get replaced with a single input for the selected item and a list of list items. 

## Question?
Is there a way to put a title attribute on the options that will be passed to the list items? Without having to update the DOM after the list has been generated?

**Comment by webbiesdk** [comment]
angular-materialize doens't contain the code that renders the select-options, materialize has that code (https://github.com/Dogfalo/materialize). 

You need to raise the issue with them. 

(Tell them to pass the `title` attribute of the options to the rendered ``li` tags).
