### ISSUE TITLE
Can´t npm install

### ISSUE THREAD

**Issue by marcellopato** [krescruz/angular-materialize#209]
npm install with problems
...

`351 error Windows_NT 10.0.14393
352 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
353 error node v6.9.1
354 error npm  v3.10.8
355 error code ETARGET
356 error notarget No compatible version found: uglify-js@^3.0.1
356 error notarget Valid install targets:
356 error notarget 2.7.5, 2.7.4, 2.7.3, 2.7.2, 2.7.1, 2.7.0, 2.6.4, 2.6.3, 2.6.2, 2.6.1, 2.6.0, 2.5.0, 2.4.24, 2.4.23, 2.4.22, 2.4.21, 2.4.20, 2.4.19, 2.4.18, 2.4.17, 2.4.16, 2.4.15, 2.4.14, 2.4.13, 2.4.12, 2.4.11, 2.4.10, 2.4.9, 2.4.8, 2.4.7, 2.4.6, 2.4.5, 2.4.4, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.6, 2.3.5, 2.3.4, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
357 error notarget This is most likely not a problem with npm itself.
357 error notarget In most cases you or one of your dependencies are requesting
357 error notarget a package version that doesn't exist.
357 error notarget
357 error notarget It was specified as a dependency of 'angular-materialize'
358 verbose exit [ 1, true ]`

**Comment by webbiesdk** [comment]
Well, here is the thing, i just initialized an empty project, then called `npm install angular-materialize`, and that worked. 

So unless you can give some further details, so I can actually replicate your problem, this issue is closed.
