### ISSUE TITLE
Need to update plugin options to camelcase

### ISSUE THREAD

**Issue by bigjollygiant14** [krescruz/angular-materialize#218]
## Describe the error in 1 sentence
As of 1/25/17, plugin options were standardized to camelcase, breaking multi-word options.
...

## Steps to reproduce

* Add carousel to page
* Add `fullWidth="true"` to element
* Observe full width is not applied

## What exactly is supposed to happen
* Carousel Item should be full width
...

## What exactly does happens
* Carousel item is not affected by addition of property
...

## A link to a page clearly demonstrating the issue
https://github.com/Dogfalo/materialize#changelog

You can use this: http://jsfiddle.net/Lvc0u55v/5757/ as a starting point (although the libraries might be old in that JSFiddle, which is your problem).

Since a lot of issues tend to be people not including all the dependencies,
or some other issue not directly caused by angular-materialize,
you cannot expect us to copy paste code in order to replicate your issue.
If no link to a page where the issue is present is provided,
expect the issue to be closed.

**Comment by webbiesdk** [comment]
Fixed by #219.
