### ISSUE TITLE
Parallax

### ISSUE THREAD

**Issue by COMPsmith** [krescruz/angular-materialize#22]
Im having issues getting parallax images to initialize and stumbled on your plugin.  I dont see anything mentioned about any fixes for parallax in your documentation so maybe it works and Im doing something wrong.  

I have a simple test site that has an index.html. then a partial.html. The parallax container works fine in the index.html but not in the partial.html. All other materialize components seem to work fine in the partial except parallax. 

Is it something I am doing wrong or does angular break this? Can you help me out please?

**Comment by webbiesdk** [comment]
If you have a simple test site, then upload it and let us see it. 

That usually makes things easier.

**Comment by COMPsmith** [comment]
@webbiesdk Here ya go fyi Im using Yoeman, bower and grunt. Ill build it real quick and push it live on a subdomain for you to view

The parallax not showing is in home.html. The one in index.html works fine
https://github.com/COMPsmith/test/tree/25ea18e1f8277ac01a5cec2c54d7fc3bb6e6ab4d

**Comment by webbiesdk** [comment]
I see. 

In content loaded asynchronously by angular, the plugin isn't run. 
So to fix it you just have to make sure that the jQuery plugin runs whenever the content is initialized by angular. (Its what most of the directives do). 
I just added parallax to this library: b517766de57400253294117739678c9a726248bf

Hope its useful.

**Comment by COMPsmith** [comment]
Thanks! I will give this a try later tonight

**Comment by COMPsmith** [comment]
Ok so excuse my lack of knowledge as Im new to this an teaching myself as much as I can. 

I cannot get this plugin to initialize in my app. Can you take look at my git and try to explain what I am doing wrong?
https://github.com/COMPsmith/compsmith_app

I think my issue is that Im auto-bootstraping htmlApp in my index so I need to also bootstrap ng-app="materializeApp" ng-controller="BodyController" in my document which I am having issues with.

If I am wrong then please correct me or give me an example I can work with for this application.

Thanks

**Comment by COMPsmith** [comment]
@webbiesdk webbiesdk 
Ok so excuse my lack of knowledge as Im new to this an teaching myself as much as I can.

I cannot get this plugin to initialize in my app. Can you take look at my git and try to explain what I am doing wrong?

I think my issue is that Im auto-bootstraping htmlApp in my index so I need to also bootstrap ng-app="materializeApp" ng-controller="BodyController" in my document which I am having issues with.

If I am wrong then please correct me or give me an example I can work with for this application.

Thanks

**Comment by webbiesdk** [comment]
I think you just need to add `"ui.materialize"` to the list of modules that the app depend on. 

So add it to the list that currently only consists of `"ngRoute"` in app.js.

**Comment by COMPsmith** [comment]
That was it! Thanks alot. I was over thinking I needed to use angular-bootstrap. You can close this if you wish
