### ISSUE TITLE
Add support for modals

### ISSUE THREAD

**Issue by brennancheung** [krescruz/angular-materialize#23]
It would be great to have support for modals.

http://materializecss.com/modals.html

It looks like modals should be available outside of angular-materialize in the baseline materializecss but only if the modal contents are already on the page.  This is problematic in Angular because it means controllers will already have run, and also because modal contents are cluttered on the main page.

It would be nice to be able to create the DOM elements fresh and run the `ng-controller` from scratch.

**Comment by webbiesdk** [comment]
Fixed with https://github.com/krescruz/angular-materialize/pull/26
