### ISSUE TITLE
Not Found - GET https://github.com/ryepdx/node-materialize/tarball/master

### ISSUE THREAD

**Issue by mendietam** [krescruz/angular-materialize#236]
The below dependancy is not available, it seems like this repo was removed.
  
```
"dependencies": {
    "node-materialize": "https://github.com/ryepdx/node-materialize/tarball/master"
  },
```

`npm i angular-materialize` is failing with error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://github.com/ryepdx/node-materialize/tarball/master
npm ERR! 404 
npm ERR! 404  'node-materialize@https://github.com/ryepdx/node-materialize/tarball/master' is not in this registry.
```

**Comment by webbiesdk** [comment]
The issue seems to be fixed by https://github.com/krescruz/angular-materialize/pull/235.  

Can you confirm whether you think that fix looks good?

**Comment by mendietam** [comment]
yes this fix looks good.

**Comment by webbiesdk** [comment]
Should be fixed with https://github.com/krescruz/angular-materialize/pull/235
