### ISSUE TITLE
Selects multiple problems

### ISSUE THREAD

**Issue by cskiwi** [krescruz/angular-materialize#29]
Hi,

I use a service to get an object array, and using that for the select in the following way:

in controller:

``` json
$scope.teams = Team.index();
```

then in html:

``` json
<select material-select ng-model="currentTeam" class="col s6">
     <option ng-repeat="team in teams" value="[[team]]">[[team.name]]</option>
</select>
```

but when the page loads there is an empty object availible, but when I select that the real data is loaded (so I think the update in the scope isn't forwarded to the select)

then when the real data is in the dropdown the following error is in my console:

```
16:06:01.188 TypeError: $(...).offset(...) is undefined
```

also the dropdown is hidden by the card class if the height is larger, and its hiding behind buttons
![untitled](https://cloud.githubusercontent.com/assets/847540/8109002/8f8d8b20-1054-11e5-9faa-b9d70ce2de11.png)

some things I can update (like the hiding, but just letting this know that you are aware of these problems)

**Comment by webbiesdk** [comment]
Okay, the TypeError doesn't matter. Its an uncaught exception, but it doesn't break anything. 

The "the dropdown is hidden by the card class if the height is larger, and its hiding behind buttons" part. I could use a JSFiddle for that.

And with the update on teams, you are right that the select doesn't update with the scope updates. 
Not much to do about that, but in the commit above, I added the possibility that you can tell the select that when a variable changes, it should update. (Hope it makes sense, but anyway, read the commit).

**Comment by webbiesdk** [comment]
Okay, after looking at issue 36, i decided to change it a bit. 

Now, if you add the attribute `watch` to the same tag where material-select is, then material-select will re-initialize whenever the content within the select changes.
