### ISSUE TITLE
"element.is() isn't a function"

### ISSUE THREAD

**Issue by mhrvatin** [krescruz/angular-materialize#3]
When I try to use `material-select`, Angular returns an error: `undefined is not a function`. The error is produced by `element.is("select")`.

I'm not directly using `$scope` in my app. Instead, I'm using `TaxController as tax` and the following element

```
<select class="" ng-model="tax.taxTable" material-select>
  <option ng-repeat="i in [29, 30, 31, 32, 33, 34, 35, 36, 37]">{{i}}</option>
</select>
```

**Comment by webbiesdk** [comment]
Dammit, when I made it I included jQuery, and i forgot to check that I only used methods in jqLite. 

You should be able to fix it for now by including jQuery before angular, I'll look at a more permanent fix later.

**Comment by mhrvatin** [comment]
I ran into the same issued with all the components I've tried: `sideNav`, `input-field` and `select`. All works fine now that I've included(concatinated and minfied) jQuery before Angular.

**Comment by webbiesdk** [comment]
Upon further inspection, jQuery needs to included for the materialize library to work. 

So jQuery has to be included anyway. 

I might write a line about that in the index.html file, but I see no reason to remove the jQuery requirement.
