### ISSUE TITLE
overlay date picker 

### ISSUE THREAD

**Issue by cskiwi** [krescruz/angular-materialize#30]
hi,

when you have a date selector in a card, it hides behind your card the moment you click on a date: lfirst time opening is fine:

![image](https://cloud.githubusercontent.com/assets/847540/8129360/d8cb4dcc-1108-11e5-8b82-447c758dfc7e.png)

then when selecting something the following happens:

![image](https://cloud.githubusercontent.com/assets/847540/8129370/e464573c-1108-11e5-900c-fb06ee5a0760.png)

but once you do the following this is fixed:

``` css
.card {
  overflow: visible;
}
```

**Comment by nadar** [comment]
inside the input_date directive should be an optional argument added to set the container:

my example:
$timeout(function () {
                        element.pickadate({
                            container : 'body',
...
                        });
                    });

**Comment by nadar** [comment]
could look somewhat like this: https://github.com/krescruz/angular-materialize/pull/31

**Comment by krescruz** [comment]
Feature in the committed. 3f2ecd43d58beff73e0cea31d8030215d51856c5 thanks @nadar

**Comment by krescruz** [comment]
Feature in the committed. 3f2ecd43d58beff73e0cea31d8030215d51856c5 thanks @nadar

**Comment by nadar** [comment]
sorry for not providing a description inside the pr.
