### ISSUE TITLE
Materialize dose not work with ui-router

### ISSUE THREAD

**Issue by mostafabarmshory** [krescruz/angular-materialize#41]
Dear Krescruz, I faced with problem with ui-route. it is not work well.

**Comment by webbiesdk** [comment]
It's not only Krescruz that maintains this, I'm also here. 

But the information you have given is simply to little, we're gonna need a JSFiddle or a link to a page where you have the problem.

**Comment by mostafabarmshory** [comment]
Dear Webbiesdk,

First of all, thanks for your attention. I have a page which is decorated with angular-ui-router. There is a view section as follow:

```
<div ui-view="Body"></div>
```

the ui-router is configured as follow:

```
app.config(function($stateProvider, $urlRouterProvider) {
  $urlRouterProvider.otherwise('/dashbord');
  $stateProvider.state('dashbord', {
      url : '/dashbord',
      views : {
          "Body" : {
              templateUrl : 'view/body.html',
              controller : 'TreeViewController'
          },
      }
  });
});
```

I have the following line in the view/body.html:

```
<a tooltipped class="btn tooltipped col s4 offset-s4 l2 offset-l1" data-position="left" data-delay="250" data-tooltip="I am tooltip"> Left</a>
```

However, the tooltip dose not appear. By the way this works correctly without angular-ui-router.

**Comment by mostafabarmshory** [comment]
Dear all,
This is my fault. I forgot to add application dependency:

```
var app = angular.module('myapp'', [ 'ui.router', 'ui.materialize']);
```

sorry.
