### ISSUE TITLE
Is there Slider declaritive?

### ISSUE THREAD

**Issue by mostafabarmshory** [krescruz/angular-materialize#43]
Slider is included in Materialize. Is it possible to add a slider using angular-materialize?

**Comment by webbiesdk** [comment]
There is not, currently. 

However, if you are just a little familiar with angular, you should be able to make a crude implementation yourself (just look at the other directives, some of them are VERY basic). 

If you do, make a pull request so other can enjoy it.

**Comment by webbiesdk** [comment]
A pull-request had a slider, so now there is one (altough it is very simple): 
http://krescruz.github.io/angular-materialize/#slider
