### ISSUE TITLE
side-nav overlay not disappearing

### ISSUE THREAD

**Issue by gate3** [krescruz/angular-materialize#45]
Great work guys, i only just recently discovered the entire materialize framework and its wonderful. 

I'm using the data-closeonclick="true" option for side-nav. It works, but the overlay doesn't disappear sometimes and at other times it disappears as it should.

**Comment by webbiesdk** [comment]
This sounds like a bug with materialize. 

Check to see if [Materialize](https://github.com/Dogfalo/materialize) also has this bug, and in that case report it with them. 

Angular-materialize is just simple directives that start use Materialize code, so the bug might very well be at their end.

**Comment by gate3** [comment]
Thanks for the response. I'm actually using the angular-materialize on a phonegap android app and it seems to work fine on the mobile device. I will test this on materialize alone as well and send a message to the authors. Thank you again

**Comment by webbiesdk** [comment]
Good, reopen this issue if the problem turns our to be with angular-materialize
