### ISSUE TITLE
Weird selection/line in the background when using date picker on Chrome

### ISSUE THREAD

**Issue by harpster604** [krescruz/angular-materialize#46]
When using input-date and opening the date picker, there is a weird blue selection that occurs in the background. This occurs approximately 800px above the date input, so make sure the window height is greater than 800px. I have attached an image showing this happening on the angular-materialize docs page. This does not seem to happen on the original materializecss.com date picker.

I have tested in Chrome 43. It does not seem to happen in Safari.

Any way to fix this? It looks a bit ugly on a production site. The selection remains when the date picker is closed, until you click elsewhere on the screen.

![screen shot 2015-07-13 at 10 11 18 pm](https://cloud.githubusercontent.com/assets/671838/8666931/0482c3a2-29ad-11e5-877b-8a44178f2b77.png)

**Comment by webbiesdk** [comment]
Hmmm, not sure why this happens. 

I think it is a bug in the [materialize code](https://github.com/Dogfalo/materialize), but it doesn't happen in their example (which is initialized at a slightly different time). 

It can be solved by adding the following CSS: 

```
#inputCreated_root {outline: none;}
```

Which the above commit does.
