### ISSUE TITLE
Multiple Initialization in material select

### ISSUE THREAD

**Issue by Nigatsu** [krescruz/angular-materialize#47]
When I was trying to use select from materialize with angular i saw weird triangle (caret) appended to input-field after each change in select. When I was search for solution I find in materialSelect directive code that initializing material-select after every change. Is it necessary? I remove last "if" and problem disappeared.

Edit: In my project I use materialize in 0.97.0 version. When I downgrade to lower version it solve the problem. Maybe you could add fix to this project that let him work with latest materialize?

**Comment by cskiwi** [comment]
This still exists for me using v0.97.0 of materializecss and download on commit: 2287ff4eacd72b9d1a7e6b5bde415c184071495b and every time I switch a caret appears

![](http://i.imgur.com/aqs2529.png)

**Comment by Nigatsu** [comment]
Sadly, fix for this problem is not merged yet

**Comment by webbiesdk** [comment]
Hey, a man can take a vacation. 

And besides, the "fix" didn't fix anything, at most it delayed the problem. 

So for now, I've pushed an ugly fix for an ugly problem, I just remove all the ".caret" every-time i re-initialize.
