### ISSUE TITLE
build tabs via ng-repeat?

### ISSUE THREAD

**Issue by cskiwi** [krescruz/angular-materialize#51]
say you want to generate the tabs dynamicly, you would have to do the following right?

``` html
<div class="row">
    <div class="col s12">
        <ul class="tabs" tabs>
            <li class="tab col s3" ng-repeat="detailTab in tabUsers"><a ng-href="#{{detailTab.name}}">{{detailTab.name}}</a></li>
        </ul>
    </div>
    <div ng-repeat="detailTab in tabUsers" id="{{detailTab.name}}" class="col s12">{{detailTab.content}}</div>
</div>
```

and with the follwoing in the controller:

``` javascript
$scope.tabUsers = [
    {
        name: "test",
        content: "Stuff"
    },
    {
        name: "test2",
        content: "Stuff2"
    }
];
```

this would work you think?
but not I'm getting the following:
`TypeError: Cannot read property 'hash' of undefined`

**Comment by cskiwi** [comment]
nevermind found it:

had to put a timeout in the ui.materialize.tabs

**Comment by ramkumarvss** [comment]
Please atleast add the timeout to this issues. we are not able to get the indicator.

**Comment by escapar** [comment]
Same problem , solved by adding timeout.
