### ISSUE TITLE
dateFormat how to use it?

### ISSUE THREAD

**Issue by cskiwi** [krescruz/angular-materialize#52]
hi,

I have a date that comes in via the following format: `17-07-2015`
how would you make it so it doesn't say: `invalid date` without splitting the date and converting it myself to `yyyy-MM-dd`

I see some stuff on UTC, but not understanding where I can access them

For now I rewrote the link function of the date: to this;

``` javascript
ngModelCtrl.$formatters.unshift(function (modelValue) {
    if (modelValue) {
        var date;
        var parts = modelValue.split("-");
        if (parts.length > 0 && parts[2].length == 4) { // other type format
            date = new Date(parts[2], parts[1], parts[0]);
        } else {
            date = new Date(modelValue);
        }
        return (angular.isDefined(scope.format)) ? date.format(scope.format) : date.format('d mmmm, yyyy');
    }
    return null;
});
```

**Comment by dcoferraz** [comment]
+1

**Comment by webbiesdk** [comment]
I don't know, it was @ch0c4 that made most of it, so he is probably the right guy to ask.

**Comment by ch0c4** [comment]
Hi,

sry for the late answer but `format` doesn't work ?

```
<input input-date format="dd-mm-yyyy" />
```

**Comment by ndraiman** [comment]
I'm putting format as "dd/mm/yyyy" but the input box shows "mm/dd/yyyy"
any idea how to fix that?

also,is it intended that the Datepicker changes the model from Date object to string?
shouldn't the format only control how it is displayed?

**Comment by farhatmo** [comment]
Hello, I have the same bug using the date format dd/mm/yyyy : 

On the link function i found this : 
`link: function (scope, element, attrs, ngModelCtrl) {

```
                ngModelCtrl.$formatters.unshift(function (modelValue) {
                    if (modelValue) {
                        var date = new Date(modelValue);
                        return (angular.isDefined(scope.format)) ? date.format(scope.format) : date.format('d mmmm, yyyy');
                    }
                    return null;
                });`
```

The default dateformat is already altered by `dateFormat()` function so `var date = new Date(modelValue)` take by default the mm/dd/yyyy format rather then dd/mm/yyyy. 

To avoid this i keep the default format dd MMM yyy .

**Comment by ndraiman** [comment]
I wanted to keep using the dd/mm/yyyy format, 
so I  wrote a method that will convert the string back to a Date object and set it to execute in `on-set`
