### ISSUE TITLE
Range thumb

### ISSUE THREAD

**Issue by cskiwi** [krescruz/angular-materialize#55]
Hi,

I'm trying to show the range tooltip when using the materializecss range thingy, but in the code of materialize I can't seem to find a function that does this, or I might be overlooking something

``` html
<form action="#">
    <p class="range-field">
        <input type="range" id="test5" min="0" max="100" />
     </p>
</form>
```

and in the materializecss javascript you can find the relavant code @ line 2614, or the input[type] handling @ line 2454

**Comment by webbiesdk** [comment]
There is no directive that does anything with ranges.
I looked at the [Materialize code](https://github.com/Dogfalo/materialize/blob/master/dist/js/materialize.js#L2610) and it seems that ranges are initialized at document ready only, and cannot be initialized later. 
So not only are there not a directive for it, with the current Materialize code, there cannot be (unless a lot of code is copied). 

I think you should create an issue with Materialize, if you want it to be possible to have dynamically created input ranges.
