### ISSUE TITLE
Paginator

### ISSUE THREAD

**Issue by jaynakus** [krescruz/angular-materialize#57]
Please change scope type of pageSize and total from '@' to '='. This is to have paginator dynamically change itself when different data counts received from server.

**Comment by JonathanGuo** [comment]
It should work fine with '@' . The variable pageSize is needed to be calculated in your code and then pass to the directive.

At my point of view, there is no need to change '@' to '='. Because the pagination directive doesn't update the pageSize at all. The directive only uses pageSize to calculate pageCount.

``` JavaScript
var yourCollection = [1,2,3,4,5];
```

``` html
<pagination page-size="{{ yourCollection.length }}" ...>
```

**Comment by jaynakus** [comment]
Imagine a situation where data is loaded from server page by page. On first page call the total data was 50 items. If I have 10 items per page, when I call the second page, meanwhile, the total item size has grown to 60. Will I have a chance to load 6th page without reloading whole web-site?

**Comment by crisryantan** [comment]
Can the total also change from '@' to '='? I would like it to be dynamic for instances like deleting items in a list that the pagination is using.

**Comment by crisryantan** [comment]
I think this is based from https://github.com/brantwills/Angular-Paging and page,pageSize and total is now two-way data binding in the latest commit. check it out: https://github.com/brantwills/Angular-Paging/blob/master/dist/paging.js

**Comment by webbiesdk** [comment]
If there is any issues with the above merge, let me know and I'll re-open this.

**Comment by degs098** [comment]
I already try this and it didn't work 
`<pagination
									    page="1"
									    page-size="{{arrayPreguntas.length}}"
									    total="50"
									    show-prev-next="true"
									    use-simple-prev-next="false"
									    dots="...."
									    hide-if-empty="false"
									    adjacent="2"
									    scroll-top="false"
									    pagination-action="cambiarPregunta(page)" />`
![image](https://cloud.githubusercontent.com/assets/13020015/21538577/8531e8de-cd6c-11e6-90e7-cf2c2b5613e1.png)
