### ISSUE TITLE
Cannot get <select> element to display

### ISSUE THREAD

**Issue by r-pluss** [krescruz/angular-materialize#63]
I'm unable to reproduce the material select example at http://krescruz.github.io/angular-materialize/#select

See http://jsbin.com/vanuxunise for minimal example taken from github.io site.

When inspecting the github.io page, I see that "select-wrapper" element is created in the DOM. However, it does not appear to be created in the JSBin example or in other attempts I have made to work with it.

Adding the "browser-default" element class to the select element does cause the element to render.

Can anyone see what example I'm missing here? I'm probably overlooking something, but I haven't been able to find anything in the documentation or source that differs from the JSBin example.

Thanks.

**Comment by webbiesdk** [comment]
Yep, you forgot to include jQuery. 

It says that you need to include jQuery in the "About angular-materialize" section in http://krescruz.github.io/angular-materialize/. 

This is because this isn't a angular rewrite of Materialize, this is just directives that interact with the Materialize code. So since Materialize requires jQuery, so do we.

**Comment by r-pluss** [comment]
Yes, I realize jQuery is a requirement.

If you look at the <a href="http://jsbin.com/vanuxunise/edit?html,output">JSBin</a> I posted, you will see that the CDN for jQuery was included. 

Thanks for the fast response, but unfortunately this doesn't address my question.

**Comment by webbiesdk** [comment]
I just looked at the console output, so i didn't spot the exact error. 

What happened is that you had jQuery after AngularJS, in which case AngularJS doesn't use the full jQuery. And we use the jQuery from AngularJS, so we require that jQuery is before AngularJS. 

You've changed the page, so I don't get the same error, but your includes are still not in order. 
Have them like this, and then it works. 

```
<script src="https://code.jquery.com/jquery-2.1.1.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
```

**Comment by r-pluss** [comment]
Going back to look at the JSBin to make the dependencies were in the correct order allow me to the see that the source of the error was having jQuery listed twice, once before angular and once before materialize. I figure it would be a dumb error, but not that dumb...

Thanks so much for your help.
