### ISSUE TITLE
Does angular-materialize work with jquery Lite

### ISSUE THREAD

**Issue by dcoferraz** [krescruz/angular-materialize#66]
I have a ongoing project that uses jquery Lite as a dependency and cannot change to another jQuery version as describe as necessary. That would take too much time to change.

Is that possible?

Thank you.

**Comment by webbiesdk** [comment]
angular-materialize requires jQuery because Materialize requires jQuery. 

Since Materialize is not going to drop the jQuery requirement (because its not an Angular application), this project isn't going to either. 

So no, not possible to use jQuery Lite instead of the full jQuery.
