### ISSUE TITLE
Enter the date manual

### ISSUE THREAD

**Issue by cskiwi** [krescruz/angular-materialize#74]
hi,

I'm wondering if there is an option to input the date manual so not the datepicker.
But if the user wants it would still be available.

Mostly because I'm using it for defining a time period, which can be 5 year, so then you would have to click 60 times on the month thingy, so it would be easier if you could just lower the year number manually

**Comment by webbiesdk** [comment]
This is not something currently supported. 
And i think this is something you should ask the Materialize guys about, because we cant support it before they do. 

Here is the documentation from Materialize in the date-picker. 
http://materializecss.com/forms.html#date-picker
