### ISSUE TITLE
Module fails to load due to some exception

### ISSUE THREAD

**Issue by PabloValor** [krescruz/angular-materialize#77]
Hello,

I'm having the following error when I injected ui.materialize and ui.router modules:
![image](https://cloud.githubusercontent.com/assets/6534833/10062748/789c4cd2-623c-11e5-8c62-894ce8c7b621.png)

so I get the following error:

Error: $injector:modulerr
Module Error
Description
This error occurs when a module fails to load due to some exception. The error message above should provide additional context.

I really appreciate any hint,
Regards.

**Comment by webbiesdk** [comment]
Does this help?
http://stackoverflow.com/questions/18287482/angularjs-1-2-injectormodulerr#answer-18287586

You might have forgotten to include one of the JavaScript files that contain one of the modules you are loading.

**Comment by PabloValor** [comment]
Hi webbiesdk, that was my problem.
Thanks!
