### ISSUE TITLE
scope values can't be seen in modal div

### ISSUE THREAD

**Issue by sayus2884** [krescruz/angular-materialize#78]
Hi. I'm trying to add my parent controller's scope value inside my modal div but it just wouldn't show. Any ideas?

HMTL

```
<div ng-controller="projectsController">          
    ...

    <div ng-repeat="project in projects">

        <div data-target="demoModal" modal>             
            <h6>{{project.name}}</h6>                
        </div>

    </div>

    <project-modal></project-modal>

    ...   
</div>
```

I'm a bit new to Angular and  might have missed something.

**Comment by dcoferraz** [comment]
Could you make an example like on a codepen on something of the kind?
Using the developer tools on Chrome, does the console show any errors?

**Comment by kdembler** [comment]
Hey.
I'm having the same issue. Scope value fails to display after init.
Here's codepen: http://codepen.io/anon/pen/VvGwpg
I don't see any errors in Console. I tried some tricks, like changing value after render, but it doesn't seem to work.

**Comment by webbiesdk** [comment]
The above commit fixes @kdembler issue. But I'm not sure whether or not it fixes the original issue.

**Comment by webbiesdk** [comment]
Closed for now, if the above commit didn't fix the issue, then I'll re-open it.
