### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by ghost** [krescruz/angular-materialize#8]
Have you thought about adding a library to bower?

**Comment by webbiesdk** [comment]
The library currently doesn't have a version, or something you could call a release. 
I believe that is needed for it to be in any kind of repository. 

Also I have no experience with bower. 

So what if you create the necessary files (just put 0.1.0 as the version), and make a pull request where you write what commands we needs to run.

**Comment by krescruz** [comment]
We are working to send our repository to bower, thanks for the suggestion.

**Comment by ghost** [comment]
Ok, thanks.

**Comment by 40x** [comment]
Is this available on bower yet? Can you please add it in the read me?

**Comment by webbiesdk** [comment]
Yes it is on bower, we had to first get another guy to remove his angular-materialize package from bower (as can be seen in #9). 

The package is called [angular-materialize](http://bower.io/search/?q=angular-materialize) on bower.

I'll make a small addition to the readme.
