### ISSUE TITLE
 Cannot read property 'replace' of undefined in select

### ISSUE THREAD

**Issue by NetanelBasal** [krescruz/angular-materialize#84]
I am looping on array and creating selects elements and when I am using the class default-browser its works fine but when I remove this class and use the materialize design I get this error:

 Cannot read property 'replace' of undefined.

``` html
<div ng-repeat="work in upw.workData track by $index">

         <div>
                        <select name="startDate" ng-model="work.start_date.month"
                                ng-options="mon for mon in upw.months"
                                material-select>
                            <option value="">Month</option>
                        </select>

                    </div>    
</div>

```

**Comment by webbiesdk** [comment]
We need a JSBin link or something. Because these issues are sometime due to dependency issues or similar, which we can't see from the code you have posted. 

Closed until further info.

**Comment by PabloPG** [comment]
I have the same problem, but the select are changing my model
cliente.pais = 31, after material-select load , changed to cliente.pais = 1 (first id)

$scope.paises is a http.get and i get client form in a $http.get too

```
<select id="pais" ng-model="cliente.pais" material-select watch>
     <option value="{{p.id}}" ng-repeat="p in paises">{{p.name}}</option>
</select>
```

**Comment by webbiesdk** [comment]
If you have the same problem, then maybe you can create an example on JSFiddle, JSBin or similar, where the issue is present.
