### ISSUE TITLE
LeanModal/Modal settings

### ISSUE THREAD

**Issue by Frankistan** [krescruz/angular-materialize#87]
Hi, in Materializecss we can set this options: 
      dismissible: true, // Modal can be dismissed by clicking outside of the modal
      opacity: .5, // Opacity of modal background
      in_duration: 300, // Transition in duration
      out_duration: 200, // Transition out duration
      ready: function() { alert('Ready'); }, // Callback for Modal open
      complete: function() { alert('Closed'); } // Callback for Modal close

So, as a directive, where and how can we modify/set this options? inside the Controller? at the end of the index.html in a script tag?

**Comment by webbiesdk** [comment]
Currently it is only the `dismissible`, `opacity`, `inDuration` and `outDuration` options there are available in our implementation. 
You set them by setting attributes on the same element that has the "modal" attribute. 
Like the following (partly copy-paste from index.html). 

```
<!-- Modal Trigger -->
<div class="col">
    <a class='btn' href='#demoModal' modal opacity="0.8" out-duration="100" >Show Modal</a>
</div>
<div input-field  class="col s4">
    <input type="text" ng-model="dummyInputs.modalInput">
    <label>Modal header</label>
</div>
<!-- Modal Structure -->
<div id="demoModal" class="modal">
    <div class="modal-content">
        <h4>{{dummyInputs.modalInput}}</h4>
        <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
</div>
```

If you want more options, you can implement it yourself and send a pull-request. We would be happy to see that.
