### ISSUE TITLE
Why does the Select not line up ?

### ISSUE THREAD

**Issue by TkNeo** [krescruz/angular-materialize#93]
If you look at my code, you will see that the select dropdown is laid out higher than the other input fields. What am i doing wrong ?

http://plnkr.co/edit/yd0vmwNzMwEn9nUqdvqB?p=info

**Comment by MichaelDeBoey** [comment]
You need to add a `input-field` class to the `div`-wrapper

**Comment by webbiesdk** [comment]
Or you need to add a div wrapper with the `input-field` class. In any case, this question is answered.
