### ISSUE TITLE
Using the "multiple" attribute on <select> has issues when setting Angular ng-model

### ISSUE THREAD

**Issue by neonash7777** [krescruz/angular-materialize#95]
<select multiple ng-model="myModel.myArrayOfStrings">
  <option ng-repeat="option in myModel.myOptions track by $index" value="{{option.value}}>{{option.name}}</option>
</select>

Using multiple doesn't keep the model in sync.
1) The control value will only show the name of the first selected item from the model and not a comma separated list from the initial model.
2) Options are not properly checked from the model.
3) Checking/Unchecking options does not properly update the model.
4) Including any space or returns/line feeds between the <option> tags and the {{}} will prevent the initial value from the model to be loaded.

**Comment by webbiesdk** [comment]
Need code example, make an example on something like JSBin, and post the link here. 

Closed until then.
