### ISSUE TITLE
TypeError: element.dropdown is not a function

### ISSUE THREAD

**Issue by MorleyMinde** [krescruz/angular-materialize#96]
I got the error as the title suggests when using  the drop down component as below:

```
<!-- Dropdown Trigger -->
<a class='dropdown-button btn' href='javascript:void(0);' data-activates='demoDropdown' dropdown data-hover="true">
This is a dropdown
</a>

<!-- Dropdown Structure -->
<ul id='demoDropdown' class='dropdown-content'>
    <li><a href="javascript:void(0);">Link 1</a></li>
    <li><a href="javascript:void(0);">Link 2</a></li>
    <li><a href="javascript:void(0);">Link 3</a></li>
    <li><a href="javascript:void(0);">Link 4</a></li>
    <li><a href="javascript:void(0);">Link 5</a></li>
</ul>
```

The jQuery file is already included above the angular-materialize.js file

**Comment by webbiesdk** [comment]
is the materialize JS file also included? 

You need to provide an example that i can run, on something like JSFiddle, otherwise I won't look at it.

**Comment by ibrahimmumcu** [comment]
Hey @MorleyMinde,

I've got the same issue, after re-ordered js files works like a charm!

I dont know which dependency you are using but here is my lib.js file order:

jquery-2.1.1.js
materialize.js 
angular.js
angular-ui-router.js (you dont have to use this library)
angular-materialize.js

Hope you can make this work,
Thanks.

**Comment by ronaldaraujo** [comment]
@ibrahimmumcu thanks! :)

**Comment by DavidGoussev** [comment]
@ibrahimmumcu thanks so much!  That solution was just what I needed!

**Comment by jamees** [comment]
thanks @ibrahimmumcu
