### ISSUE TITLE
Pagination numbers error

### ISSUE THREAD

**Issue by PabloPG** [krescruz/angular-materialize#98]
Hi, when i click on a number, shows this:

![Image of error](http://i.imgur.com/MViceHe.png)

Code:

```
<div class="row">
    <pagination page="currentPage" page-size="numPerPage" total="totalItems" show-prev-next="true">
</div>
```

**Comment by webbiesdk** [comment]
Have a link to codepen or similar, otherwise we will spend to much time replicating the issue.

**Comment by webbiesdk** [comment]
Issue can be reopened if you give more information.
